"""All schema generated

Revision ID: 92acc645abec
Revises: 
Create Date: 2025-06-16 22:48:59.060669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92acc645abec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_area',
    sa.Column('assessment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('document_metadata',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('number_of_pages', sa.Integer(), nullable=True),
    sa.Column('doc_size_kb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_document_metadata_doc_id'), 'document_metadata', ['doc_id'], unique=False)
    op.create_table('document_type',
    sa.Column('doc_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_type_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('doc_type_id')
    )
    op.create_table('prompt',
    sa.Column('prompt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criteria', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_table('assessment_area_prompt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_area.assessment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.prompt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'prompt_id', name='_assessment_prompt_uc')
    )
    op.create_table('document_type_assessment_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_type_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_area.assessment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.doc_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_type_id', 'assessment_id', name='_doc_type_assessment_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_type_assessment_area')
    op.drop_table('assessment_area_prompt')
    op.drop_table('prompt')
    op.drop_table('document_type')
    op.drop_index(op.f('ix_document_metadata_doc_id'), table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_table('assessment_area')
    # ### end Alembic commands ###
